services:
  redis:
    container_name: redis
    networks:
      - testnet
    image: redis:7
  rediswrapper:
    container_name: rediswrapper
    networks:
      - testnet
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      REDIS_URL: redis:6379

networks:
  testnet:
    name: testnet
