version: 2.1
orbs:
  codecov: codecov/codecov@3.2.2

executors:
  go:
    docker:
      - image: cimg/go:1.18
    resource_class: small
  node:
    docker:
      - image: cimg/node:lts
    resource_class: small

jobs:
  lint:
    executor: go
    steps:
      - checkout
      - run: make lint
  test:
    parameters:
      alpine_version:
        type: string
      go_version:
        type: string
      redis_version:
        type: string
    executor: go
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          command: make test
          environment:
            ALPINE_VERSION: << parameters.alpine_version >>
            GO_VERSION: << parameters.go_version >>
            REDIS_VERSION: << parameters.redis_version >>
      - store_test_results:
          path: results.xml
      - when:
          condition:
            and:
              - equal: [ "3.16", << parameters.alpine_version >> ]
              - equal: [ "1.18", << parameters.go_version >> ]
              - equal: [ "7", << parameters.redis_version >> ]
          steps:
            - codecov/upload
  load:
    executor: node
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run: npm install -g k6-to-junit
      - run: make load
      - store_artifacts:
          path: stats.json
      - run: cat stats.json | k6-to-junit k6-results.xml
      - store_test_results:
          path: k6-results.xml


workflows:
  version: 2
  ci:
    jobs:
      - lint
      - test:
          matrix:
            parameters:
              alpine_version: ["3.16", "3.15"]
              go_version: ["1.18", "1.17"]
              redis_version: ["7", "6", "5"]
      - load
